# Generated by Django 3.2.3 on 2022-02-10 21:44

from django.db import migrations, models
import utility_tool.models


class Migration(migrations.Migration):

    dependencies = [
        ('utility_tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='docfile',
            field=models.FileField(blank=True, null=True, storage=utility_tool.models.MyFileStorage(), upload_to='documents'),
        ),
    ]
