# Generated by Django 3.2.3 on 2022-02-11 15:32

from django.db import migrations, models
import utility_tool.models


class Migration(migrations.Migration):

    dependencies = [
        ('utility_tool', '0002_fileupload_docfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sd_cost_file',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, storage=utility_tool.models.MyFileStorage(), upload_to='documents'),
        ),
        migrations.AddField(
            model_name='sd_dec_file',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, storage=utility_tool.models.MyFileStorage(), upload_to='documents'),
        ),
        migrations.AddField(
            model_name='sd_eva_file',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, storage=utility_tool.models.MyFileStorage(), upload_to='documents'),
        ),
        migrations.AddField(
            model_name='sd_evam_file',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, storage=utility_tool.models.MyFileStorage(), upload_to='documents'),
        ),
        migrations.AddField(
            model_name='sd_iw_file',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, storage=utility_tool.models.MyFileStorage(), upload_to='documents'),
        ),
        migrations.AddField(
            model_name='sd_makedec_file',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, storage=utility_tool.models.MyFileStorage(), upload_to='documents'),
        ),
        migrations.AddField(
            model_name='sd_mapp_file',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, storage=utility_tool.models.MyFileStorage(), upload_to='documents'),
        ),
        migrations.AddField(
            model_name='sd_scr_file',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, storage=utility_tool.models.MyFileStorage(), upload_to='documents'),
        ),
        migrations.AddField(
            model_name='sd_solopt_file',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, storage=utility_tool.models.MyFileStorage(), upload_to='documents'),
        ),
        migrations.AddField(
            model_name='sd_st_file',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, storage=utility_tool.models.MyFileStorage(), upload_to='documents'),
        ),
        migrations.AddField(
            model_name='solution_options',
            name='file_attachment1',
            field=models.FileField(blank=True, null=True, storage=utility_tool.models.MyFileStorage(), upload_to='documents'),
        ),
        migrations.AddField(
            model_name='solution_options',
            name='file_attachment2',
            field=models.FileField(blank=True, null=True, storage=utility_tool.models.MyFileStorage(), upload_to='documents'),
        ),
        migrations.AddField(
            model_name='solution_options',
            name='file_attachment3',
            field=models.FileField(blank=True, null=True, storage=utility_tool.models.MyFileStorage(), upload_to='documents'),
        ),
        migrations.AddField(
            model_name='solution_options',
            name='file_attachment4',
            field=models.FileField(blank=True, null=True, storage=utility_tool.models.MyFileStorage(), upload_to='documents'),
        ),
        migrations.AddField(
            model_name='solution_options_storage',
            name='solopt_file',
            field=models.FileField(blank=True, null=True, storage=utility_tool.models.MyFileStorage(), upload_to='costutility/static'),
        ),
    ]
