from django.conf.urls import *
from django.contrib import admin
from utility_tool import views as myviews
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^index.html$', myviews.index, name='index'),
    url(r'^Home.html$', myviews.Home, name='Home'),
    url(r'^Steps.html$', myviews.Steps, name='Steps'),
    url(r'^tutorials.html$', myviews.tutorials, name='tutorials'),
    url(r'^tutorials_dm.html$', myviews.tutorials_dm, name='tutorials_dm'),
    url(r'^tutorials_ca.html$', myviews.tutorials_ca, name='tutorials_ca'),
    url(r'^tutorials_rc.html$', myviews.tutorials_rc, name='tutorials_rc'),    
    url(r'^Contact-Us.html$', myviews.ContactUs, name='ContactUs'), 
    url(r'^Resources-Guidance.html$', myviews.RG, name='RG'),              
    url(r'^Who-We-Are.html$', myviews.WhoWeAre, name='WhoWeAre'),
    url(r'^Our-Team.html$', myviews.OurTeam, name='OurTeam'),  
    url(r'^Online.html$', myviews.Online, name='Online'),
    #url(r'^$', myviews.about, name='about'),
    url(r'^$', myviews.Home, name='Home'),
    url(r'^logout.html$', myviews.logout, name='logout'),
    url(r'^temp.html$', myviews.temp, name='temp'),
    url(r'^utility_tool/stakeholders/stakeholders.html$', myviews.stakeholders, name='stakeholders'),
    url(r'^utility_tool/stakeholders/add_stakeholder.html$', myviews.add_stakeholder, name='add_stakeholder'),
    url(r'^utility_tool/stakeholders/(?P<st_id>\d+)/edit_stakeholder.html$', myviews.edit_stakeholder, name='edit_stakeholder'),
    url(r'^utility_tool/stakeholders/(?P<st_id>\d+)/delete_stakeholder.html$', myviews.delete_stakeholder, name='delete_stakeholder'),
    url(r'^utility_tool/decisions/solution_options/send_email.html$', myviews.send_email, name='send_email'),
    url(r'^utility_tool/stakeholders/import_excel.html$', myviews.import_excel, name='import_excel'),
    url(r'^utility_tool/stakeholders/export_stakeholders.html$', myviews.export_stakeholders, name='export_stakeholders'),

    url(r'^utility_tool/users/login.html$', myviews.login, name='login'),
    url(r'^utility_tool/users/register.html$', myviews.register, name='register'),
    url(r'^utility_tool/users/forgot.html$', myviews.forgot, name='forgot'),
    url(r'^utility_tool/users/change_password.html$', myviews.change_password, name='change_password'),

    url(r'^utility_tool/decisions/handsontable.html$', myviews.handsontable, name='handsontable'),
    url(r'^utility_tool/decisions/add_decision.html$', myviews.add_decision, name='add_decision'),
    url(r'^utility_tool/decisions/decisions_list.html$', myviews.decisions_list, name='decisions_list'),
    url(r'^utility_tool/decisions/pa_setup.html$', myviews.pa_setup, name='pa_setup'),
    url(r'^utility_tool/decisions/(?P<dec_id>\d+)/view_decision.html$', myviews.view_decision, name='view_decision'),
    url(r'^utility_tool/decisions/(?P<dec_id>\d+)/edit_decision.html$', myviews.edit_decision, name='edit_decision'),
    url(r'^utility_tool/decisions/(?P<dec_id>\d+)/dupl_decision.html$', myviews.dupl_decision, name='dupl_decision'),
    url(r'^utility_tool/decisions/download_demo.html$', myviews.download_demo, name='download_demo'),
    url(r'^utility_tool/decisions/(?P<dec_id>\d+)/delete_decision.html$', myviews.delete_decision, name='delete_decision'),
    url(r'^utility_tool/decisions/(?P<dec_id>\d+)/share_dec.html$', myviews.share_dec, name='share_dec'),
    url(r'^utility_tool/decisions/(?P<dec_id>\d+)/unshare_dec.html$', myviews.unshare_dec, name='unshare_dec'),   

    url(r'^utility_tool/decisions/solution_options/menu.html$', myviews.solutions_options_menu, name='solutions_options_menu'),
    url(r'^utility_tool/decisions/solution_options/(?P<dec_id>\d+)/question1.html$', myviews.question1, name='question1'),
    url(r'^utility_tool/decisions/solution_options/question1.html$', myviews.question2, name='question2'),
    url(r'^utility_tool/decisions/solution_options/question3.html$', myviews.question3, name='question3'),
    url(r'^utility_tool/decisions/solution_options/identify_st.html$', myviews.identify_st, name='identify_st'),
    url(r'^utility_tool/decisions/add_supp_doc.html$', myviews.add_supp_doc, name='add_supp_doc'),
    url(r'^utility_tool/decisions/solution_options/add_solopt_det.html$', myviews.add_solopt_det, name='add_solopt_det'),
    url(r'^utility_tool/decisions/solution_options/solopt_archive.html$', myviews.solopt_archive, name='solopt_archive'),
    url(r'^utility_tool/decisions/solution_options/solopt_storage.html$', myviews.solopt_storage, name='solopt_storage'),
    url(r'^utility_tool/decisions/solution_options/Solution Options template.xlsx$', myviews.xlsx1, name='xlsx1'),
    url(r'^utility_tool/decisions/(?P<dec_id>\d+)/solution_options/view_solopt_det.html$', myviews.view_solopt_det, name='view_solopt_det'),
    url(r'^utility_tool/decisions/solution_options/add_st_solopt.html$', myviews.add_st_solopt, name='add_st_solopt'),
    url(r'^utility_tool/decisions/solution_options/add_st_scrcr.html$', myviews.add_st_scrcr, name='add_st_scrcr'),
    url(r'^utility_tool/decisions/solution_options/add_st_evacr.html$', myviews.add_st_evacr, name='add_st_evacr'),
    url(r'^utility_tool/decisions/solution_options/add_st_iw.html$', myviews.add_st_iw, name='add_st_iw'),
    url(r'^utility_tool/decisions/solution_options/add_st_all.html$', myviews.add_st_all, name='add_st_all'),
    url(r'^utility_tool/decisions/solution_options/assign_tasks.html$', myviews.assign_tasks, name='assign_tasks'),
    #url(r'^utility_tool/decisions/solution_options/add_iw_votes.html$', myviews.add_iw_votes, name='add_iw_votes'),
    url(r'^utility_tool/decisions/solution_options/summary.html$', myviews.summary, name='summary'),
    url(r'^utility_tool/decisions/solution_options/is_summary.html$', myviews.is_summary, name='is_summary'),
    url(r'^utility_tool/decisions/solution_options/utility_results.html$', myviews.utility_results, name='utility_results'),
    url(r'^utility_tool/decisions/solution_options/add_scr_criteria.html$', myviews.add_scr_criteria, name='add_scr_criteria'),
    url(r'^utility_tool/decisions/solution_options/add_eva_criteria.html$', myviews.add_eva_criteria, name='add_eva_criteria'),
    url(r'^utility_tool/decisions/solution_options/add_scores.html$', myviews.add_scores, name='add_scores'),
    url(r'^utility_tool/decisions/solution_options/add_measures.html$', myviews.add_measures, name='add_measures'),
    url(r'^utility_tool/decisions/solution_options/idn_measures.html$', myviews.idn_measures, name='idn_measures'), 
    url(r'^utility_tool/decisions/solution_options/export_idn.html$', myviews.export_idn, name='export_idn'),
    url(r'^utility_tool/decisions/solution_options/export_mea.html$', myviews.export_mea, name='export_mea'),
    url(r'^utility_tool/decisions/solution_options/export_results.html$', myviews.export_results, name='export_results'),
    url(r'^utility_tool/admin/export_info.html$', myviews.export_info, name='export_info'),
    url(r'^utility_tool/decisions/solution_options/restore_idn.html$', myviews.restore_idn, name='restore_idn'),
    url(r'^utility_tool/decisions/solution_options/costs1.html$', myviews.cost_setup, name='cost_setup'),
    #url(r'^utility_tool/decisions/solution_options/costs2.html$', myviews.cost_setup2, name='cost_setup2'),
    url(r'^utility_tool/decisions/solution_options/cost_table.html$', myviews.cost_table, name='cost_table'),
    url(r'^utility_tool/decisions/solution_options/decision_made.html$', myviews.decision_made, name='decision_made'),
    url(r'^utility_tool/decisions/solution_options/link.html$', myviews.link, name='link'),
    #url(r'^utility_tool/decisions/solution_options/add_scr_det.html$', myviews.add_scr_det, name='add_scr_det'),
    url(r'^utility_tool/decisions/solution_options/handsontable.html$', myviews.handsontable, name='handsontable'),
    url(r'^utility_tool/decisions/solution_options/guidance.html$', myviews.guidance, name='guidance'),
    url(r'^utility_tool/decisions/temp.html$', myviews.temp, name='temp'),
    url(r'^utility_tool/decisions/message.html$', myviews.message, name='message'),
    url(r'^utility_tool/decisions/nouser_message.html$', myviews.nouser_message, name='nouser_message'),

    url(r'^utility_tool/resources/dec_info.html$', myviews.dec_info, name='dec_info'),
    url(r'^utility_tool/resources/st_info.html$', myviews.st_info, name='st_info'), 
    url(r'^utility_tool/resources/solopt_info.html$', myviews.solopt_info, name='solopt_info'),     
    url(r'^utility_tool/resources/scr_info.html$', myviews.scr_info, name='scr_info'),
    url(r'^utility_tool/resources/eva_info.html$', myviews.eva_info, name='eva_info'), 
    url(r'^utility_tool/resources/score_info.html$', myviews.score_info, name='score_info'), 
    url(r'^utility_tool/resources/evamea_info.html$', myviews.evamea_info, name='evamea_info'),     
    url(r'^utility_tool/resources/utility_info.html$', myviews.utility_info, name='utility_info'),  
    url(r'^utility_tool/resources/costs_info.html$', myviews.costs_info, name='costs_info'),
    url(r'^utility_tool/resources/makedec_info.html$', myviews.makedec_info, name='makedec_info'),
    url(r'^utility_tool/resources/gen_info.html$', myviews.gen_info, name='gen_info'), 
    url(r'^utility_tool/resources/about_maker.html$', myviews.about_maker, name='about_maker'),

    url(r'^utility_tool/decisions/(?P<dec_id>\d+)/menu.html$', myviews.menu, name='menu'),
    url(r'^utility_tool/decisions/(?P<dec_id>\d+)/menu3.html$', myviews.menu3, name='menu3'),
    url(r'^utility_tool/decisions/(?P<dec_id>\d+)/menu4.html$', myviews.menu4, name='menu4'),

    url(r'^utility_tool/admin/import_cbcse_scrcr.html$', myviews.import_cbcse_scrcr, name='import_cbcse_scrcr'),
    url(r'^utility_tool/admin/import_cbcse_evacr.html$', myviews.import_cbcse_evacr, name='import_cbcse_evacr'),
    url(r'^utility_tool/admin/imports.html$', myviews.imports, name='imports'),
    url(r'^utility_tool/admin/usage-info.html$', myviews.usageinfo, name='usageinfo'),
    url(r'^utility_tool/admin/options.html$', myviews.options, name='options'),
    url(r'^utility_tool/admin/userlist.html$', myviews.userlist, name='userlist'),
    url(r'^utility_tool/admin/export_users.html$', myviews.export_users, name='export_users'),
    url(r'^utility_tool/admin/genadmin.html$', myviews.genadmin, name='genadmin'),
    url(r'^utility_tool/admin/updatedemo.html$', myviews.updatedemo, name='updatedemo'),
     url(r'^utility_tool/admin/upload.html$', myviews.upload, name='upload'), 
    url(r'^utility_tool/admin/(?P<dec_id>\d+)/remove_dec.html$', myviews.remove_dec, name='remove_dec'), 
    url(r'^utility_tool/admin/extract_data.html$', myviews.extract_data, name='extract_data'),
    url(r'^utility_tool/admin/extract_idn_data.html$', myviews.extract_idn_data, name='extract_idn_data'),  
    url(r'^utility_tool/admin/export_all.html$', myviews.export_all, name='export_all'),
    url(r'^utility_tool/admin/export_test.html$', myviews.export_test, name='export_test'),           
    url(r'^utility_tool/admin/export_sr.html$', myviews.export_sr, name='export_sr'),
    url(r'^utility_tool/admin/export_sr_t.html$', myviews.export_sr_t, name='export_sr_t'),
    url(r'^utility_tool/admin/export_app.html$', myviews.export_app, name='export_app'),
    url(r'^utility_tool/admin/export_app_t.html$', myviews.export_app_t, name='export_app_t'),
    #url(r'^utility_tool/admin/reglist.html$', myviews.reglist, name='reglist'),
    url(r'^utility_tool/reports/(?P<dec_id>\d+)/summary_report.html$', myviews.summary_report, name='summary_report'),
    url(r'^utility_tool/reports/(?P<dec_id>\d+)/appendices.html$', myviews.appendices, name='appendices'),
    url(r'^utility_tool/decisions/Flowchart.html$', myviews.flowchart, name='flowchart'),
    url(r'^utility_tool/users/license.html$', myviews.license, name='license'),
    url(r'^utility_tool/users/renew_license.html$', myviews.renew_license, name='renew_license'), 
    url(r'^DM Online Private Institution Tool Kit License.pdf$', myviews.private_pdf, name='private_pdf'),
    url(r'^DM Online Public Institution Tool Kit License.pdf$', myviews.public_pdf, name='public_pdf'),
    url(r'^utility_tool/users/DM Online Public Institution Tool Kit License.pdf$', myviews.return_pdf, name='return_pdf'),
    url(r'^license2.html$', myviews.license2, name='license2'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
